//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGAL.Model.Logic.SGAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class adeptomodulo
    {
        public int adeptomoduloid { get; set; }
        public Nullable<int> adeptoid { get; set; }
        public Nullable<int> moduloid { get; set; }
        public Nullable<System.DateTime> datainicio { get; set; }
        public Nullable<System.DateTime> datatermino { get; set; }
        public Nullable<bool> aprovado { get; set; }
    
        public virtual adepto adepto { get; set; }
        public virtual modulo modulo { get; set; }
    }
}
