//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGAL.Model.Logic.SGAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class adeptomissaosagrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adeptomissaosagrada()
        {
            this.adeptomissaosagrada1 = new HashSet<adeptomissaosagrada>();
        }
    
        public int adeptomissaosagradaid { get; set; }
        public Nullable<int> adeptoid { get; set; }
        public Nullable<int> missaosagradaid { get; set; }
        public string situacao { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> valortotal { get; set; }
        public Nullable<System.DateTime> datainicio { get; set; }
        public Nullable<System.DateTime> dataalteracao { get; set; }
        public Nullable<System.DateTime> datatermino { get; set; }
        public Nullable<int> adeptomissaosagradavinculoid { get; set; }
    
        public virtual adepto adepto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adeptomissaosagrada> adeptomissaosagrada1 { get; set; }
        public virtual adeptomissaosagrada adeptomissaosagrada2 { get; set; }
        public virtual missaosagrada missaosagrada { get; set; }
    }
}
