//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGAL.Model.Logic.SGAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class associacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public associacao()
        {
            this.adeptorevistasagrada = new HashSet<adeptorevistasagrada>();
            this.associado = new HashSet<associado>();
            this.livropresenca = new HashSet<livropresenca>();
        }
    
        public int associacaoid { get; set; }
        public Nullable<int> regionalid { get; set; }
        public Nullable<int> federacaoid { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> datainclusao { get; set; }
        public Nullable<System.DateTime> dataalteracao { get; set; }
        public Nullable<System.DateTime> dataabertura { get; set; }
        public Nullable<System.DateTime> datafechamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adeptorevistasagrada> adeptorevistasagrada { get; set; }
        public virtual federacao federacao { get; set; }
        public virtual regional regional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<associado> associado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<livropresenca> livropresenca { get; set; }
    }
}
