//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGAL.Model.Logic.SGAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class associado
    {
        public int associadoid { get; set; }
        public Nullable<int> associadotipoid { get; set; }
        public Nullable<int> adeptoid { get; set; }
        public Nullable<int> associacaoid { get; set; }
        public Nullable<System.DateTime> dataassociacao { get; set; }
        public Nullable<System.DateTime> dataalteracao { get; set; }
        public string observacao { get; set; }
        public string situacao { get; set; }
    
        public virtual adepto adepto { get; set; }
        public virtual associacao associacao { get; set; }
        public virtual associadotipo associadotipo { get; set; }
    }
}
