//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGAL.Model.Logic.SGAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class livropresenca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public livropresenca()
        {
            this.adeptolivropresenca = new HashSet<adeptolivropresenca>();
        }
    
        public int livropresencaid { get; set; }
        public Nullable<int> associacaoid { get; set; }
        public Nullable<int> atividadeid { get; set; }
        public Nullable<int> orientadorid { get; set; }
        public Nullable<System.DateTime> datahorareuniao { get; set; }
        public string temareuniao { get; set; }
        public string observacoes { get; set; }
    
        public virtual adepto adepto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adeptolivropresenca> adeptolivropresenca { get; set; }
        public virtual associacao associacao { get; set; }
        public virtual atividade atividade { get; set; }
    }
}
