//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGAL.Model.Logic.SGAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGALEntities : DbContext
    {
        public SGALEntities()
            : base("name=SGALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adepto> adepto { get; set; }
        public virtual DbSet<adeptolivropresenca> adeptolivropresenca { get; set; }
        public virtual DbSet<adeptomissaosagrada> adeptomissaosagrada { get; set; }
        public virtual DbSet<adeptomodulo> adeptomodulo { get; set; }
        public virtual DbSet<adeptorevistasagrada> adeptorevistasagrada { get; set; }
        public virtual DbSet<associacao> associacao { get; set; }
        public virtual DbSet<associado> associado { get; set; }
        public virtual DbSet<associadotipo> associadotipo { get; set; }
        public virtual DbSet<atividade> atividade { get; set; }
        public virtual DbSet<federacao> federacao { get; set; }
        public virtual DbSet<livropresenca> livropresenca { get; set; }
        public virtual DbSet<missaosagrada> missaosagrada { get; set; }
        public virtual DbSet<missaosagradatipo> missaosagradatipo { get; set; }
        public virtual DbSet<modulo> modulo { get; set; }
        public virtual DbSet<regional> regional { get; set; }
        public virtual DbSet<revistasagrada> revistasagrada { get; set; }
    }
}
